In [1]:
import numpy as np

In [2]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [7]:
a = np.array([5, 1, 2, 6, 4])
b = np.array([7, 1, 9, 3, 6])

In [8]:
a + b

array([12,  2, 11,  9, 10])

In [10]:
a = np.array([2, 3, 2.5])
a * 72 + np.array([120, 150, 190]) + np.array([130, 130, 130])

array([394., 496., 500.])

In [11]:
a = np.array([4,5])
b = np.array([2,1])
c = np.array([1,0])
a*2 + b*(-3) + c*5

array([7, 7])

In [13]:
import pandas as pd

data = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85],
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65],
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5],
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10],
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [14]:
data

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [22]:
data.values[:,1]-data.values[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [25]:
data.values[:,4]@np.array([10,20,30,15,5,40,20,8,20])

1348

In [26]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [27]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [35]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [36]:
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [37]:
Inc*0.87

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [39]:
Inc*0.87-Cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [41]:
a = np.array([[1, -1, 2, 4, 0], [8, 2, 0, 5, 3], [0, 1, 2, 1, 2]])
a

array([[ 1, -1,  2,  4,  0],
       [ 8,  2,  0,  5,  3],
       [ 0,  1,  2,  1,  2]])

In [42]:
b = np.array([[1,0,1,0],[0,0,2,-1],[1,0,1,1],[0,1,1,1],[1,1,0,-1]])
b

array([[ 1,  0,  1,  0],
       [ 0,  0,  2, -1],
       [ 1,  0,  1,  1],
       [ 0,  1,  1,  1],
       [ 1,  1,  0, -1]])

In [43]:
np.dot(a, b)

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

In [44]:
np.array([[2,0],[0,2]])*np.array([[1,1],[4,5]])

array([[ 2,  0],
       [ 0, 10]])