In [1]:
import numpy as np

In [2]:
v1 = [-1, 2, -7, 9]
v2 = [2, 8, 2, -1]

In [10]:
-1*2+2*8+-7*2+9*-1


-9

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
A = np.array([[1,1],[1,2]])
A.T@A

array([[2, 3],
       [3, 5]])

In [12]:
A = np.array([[1,2],[3,7]])
np.linalg.inv(A)

array([[ 7., -2.],
       [-3.,  1.]])

In [16]:
v1 = [2, 10, -2]
v2 = [3, 2, -2]
v3 = [8,14,-6]
A = np.array([v1,v2,v3]).T
A

array([[ 2,  3,  8],
       [10,  2, 14],
       [-2, -2, -6]])

In [17]:
np.linalg.matrix_rank(A)

2

In [18]:
np.linalg.det(A)

0.0

In [19]:
np.linalg.det(np.array([[5, 1],[10,2]]))

0.0

In [21]:
np.linalg.matrix_rank(np.array([[1, 1,2],[1,7,3]]))

2

In [22]:
np.linalg.matrix_rank(np.array([[4, 7, -1, 7],[2, 1, 1, 2]]))

2

In [23]:
np.linalg.matrix_rank(np.array([[4, 7, -1, 7],[-4, 2, 5, 3],[0, 9, 4, 10]]))

2