In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 5,  7, 11],
       [ 6, 11,  6],
       [ 7,  5,  5]])

In [4]:
B

array([[ 3,  3,  0],
       [-2, -2,  1],
       [ 2,  3,  0]])

In [5]:
# Поэлементное умножение
A*B

array([[ 15,  21,   0],
       [-12, -22,   6],
       [ 14,  15,   0]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[23 34  7]
 [ 8 14 11]
 [21 26  5]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[23, 34,  7],
       [ 8, 14, 11],
       [21, 26,  5]])

In [8]:
# Матричное умножение
A@B

array([[23, 34,  7],
       [ 8, 14, 11],
       [21, 26,  5]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[ 33,  54,  51],
       [-15, -31, -29],
       [ 28,  47,  40]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 9  8 11  8  5]
 [ 5  5  6 10  6]
 [ 7  8  5  9  7]]
B:
 [[ 1  3]
 [-1  1]
 [ 1  2]
 [ 1  2]
 [-1  3]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[15, 88],
       [10, 70],
       [ 6, 78]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [13]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [14]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 3 -4 -1  3]
 [-3  3 -3 -2]
 [ 2 -3  0 -4]
 [ 2 -3 -4  3]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 3 -8  0 -3]
 [-3  6  0  2]
 [ 2 -6  0  4]
 [ 2 -6  0 -3]]
DA:
 [[ 3 -4 -1  3]
 [-6  6 -6 -4]
 [ 0  0  0  0]
 [-2  3  4 -3]]


In [15]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [ ]:
b@A

In [16]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [ ]:
# матрица Грама ортогональной системы векторов
A@A.T

In [17]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [18]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [19]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [20]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [21]:
A

array([[ 5, -1,  3,  1,  2],
       [-2,  8,  5, -1,  1]])

In [22]:
x

array([1, 2, 3, 4, 5])

In [23]:
A@x

array([26, 30])

In [24]:
x@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

In [25]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [26]:
A

array([[1, 9, 8, 5],
       [3, 6, 3, 2],
       [3, 3, 3, 3],
       [0, 2, 5, 9],
       [4, 4, 1, 2]])

In [27]:
B

array([[ 1, -1,  0,  1,  1],
       [-2,  0,  2, -1,  1]])

In [29]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [30]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [31]:
A = np.array([x,y,z])

In [32]:
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [33]:
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [34]:
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [56]:
import pandas as pd

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7],
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0],
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    },
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5],
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4],
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2]
    },
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [36]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [37]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [57]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [39]:
com

array([0.2, 0.2, 0.3, 0.1, 0.1])

In [58]:
C = Price_DF.values
C

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [59]:
P = Price_DF.values
P

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [49]:
(C*P)@(np.array([1,1,1,1,1])-com).T

array([ 7.176, 10.092, 10.225, 13.408, 20.525, 55.525,  6.169, 37.875])

In [65]:
com

array([0.2, 0.2, 0.3, 0.1, 0.1])

In [63]:
(P*C)

array([[ 4.  ,  2.25,  1.  ,  0.64,  1.  ],
       [ 3.24,  6.25,  1.  ,  1.  ,  1.  ],
       [ 4.  ,  4.  ,  0.  ,  0.25,  4.  ],
       [ 3.24,  1.44,  7.84,  0.64,  4.  ],
       [ 6.25, 12.25,  4.  ,  1.  ,  2.25],
       [25.  , 25.  ,  9.  ,  4.  ,  6.25],
       [ 1.21,  1.  ,  2.25,  0.25,  2.89],
       [20.25, 16.  ,  6.25,  1.  ,  4.  ]])

In [64]:
(P*C)@com

array([ 1.714,  2.398,  2.025,  3.752,  5.225, 13.725,  1.431,  9.625])

In [55]:
1.714*7

11.998

In [67]:
np.linalg.inv(np.array([[1,2],[2,5]]))

array([[ 5., -2.],
       [-2.,  1.]])

In [70]:
round(np.linalg.det(np.linalg.inv(np.array([[2,0,0],[0,1,0],[0,0,4]]))), 3)

0.125

In [71]:
np.linalg.matrix_rank(np.array([[1,0,3,5],[0,4,5,5],[0,0,0,0],[0,0,0,0]]))

2

In [72]:
np.linalg.matrix_rank(np.array([[1,0,3,5],[0,4,5,5],[0,0,0,4],[0,0,0,0]]))

3